apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
spec:
  replicas: 1  # Scale to 1 replica
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python
        image: your-dockerhub-username/hello-world-python:latest
